# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
- repo: local
  hooks:
    - id: check-links
      name: Check Links
      description: Check links inside markdown files
      language: script
      types: ["markdown"]
      entry: ./.hooks/check-links.sh
    - id: markdown-magic
      name: Markdown Magic
      description: Execute Markdown Magic on markdown files
      language: script
      types: ["markdown"]
      entry: ./.hooks/markdown-magic-generation.sh
