@startuml(id=light_blue)
skinparam dpi 300

!define LARGE_TEXT 16
!define NORMAL_TEXT 14
!define SMALL_TEXT 12

!define BACKGROUND_COLOR white
!define BORDER_COLOR #97A5AA
!define ARROW_COLOR #97A5AA
!define FONT_NAME "Source Code Variable"
!define FONT_COLOR #414c4f

!define CLASS_BORDER_COLOR BORDER_COLOR
!define CLASS_BACKGROUND_COLOR BACKGROUND_COLOR
!define CLASS_ARROW_COLOR ARROW_COLOR
!define CLASS_ARROW_THICKNESS 1.5
!define CLASS_BORDER_THICKNESS 1.5
!define CLASS_FONT_COLOR FONT_COLOR
!define CLASS_FONT_NAME FONT_NAME

!define NOTE_BORDER_COLOR BORDER_COLOR
!define NOTE_BACKGROUND_COLOR white
!define NOTE_BORDER_THICKNESS 1.5
!define NOTE_FONT_COLOR FONT_COLOR
!define NOTE_FONT_NAME FONT_NAME

@enduml
