@startuml
!include style.iuml

skinparam class {
	FontColor CLASS_FONT_COLOR
	FontName CLAS_FONT_NAME
	FontSize LARGE_TEXT

	ArrowColor CLASS_ARROW_COLOR
	ArrowThickness 2

	BackgroundColor CLASS_BACKGROUND_COLOR
	BorderColor CLASS_BORDER_COLOR
	BorderThickness CLASS_BORDER_THICKNESS

	StereotypeFontName CLASS_FONT_NAME
	StereotypeFontColor CLASS_FONT_COLOR
	StereotypeFontSize SMALL_TEXT

	AttributeFontName CLASS_FONT_NAME
	AttributeFontColor CLASS_FONT_COLOR
	AttributeFontSize NORMAL_TEXT
}

skinparam note {
	BackgroundColor NOTE_BACKGROUND_COLOR
	BorderColor NOTE_BORDER_COLOR
	BorderThickness NOTE_BORDER_THICKNESS

	FontName NOTE_FONT_NAME
	FontColor NOTE_FONT_COLOR
}


skinparam roundcorner 8
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho

hide empty members
hide empty fields
hide circle

hide <<Hidden>>

interface Command <<interface>> {
	+execute()
}

class Receiver

class ConcreteCommand1 {
	receiver: Receiver
	+execute()
}

Command <|... ConcreteCommand1

Receiver --o ConcreteCommand1

class Invoker

Invoker o-- Command

Class Client

ConcreteCommand1 --o Client
Invoker --o Client
Receiver --o Client

@enduml
